### ISSUE TITLE
tsvector Field Already Exists

### ISSUE THREAD

**Issue by cjmochrie** [damoti/django-tsvector-field#3]
Following along with the tutorial I've added a 'search' field to an existing model and generated the migration file. But when I run 'migrate' the migrations fails with a ProgrammingError 'name-of-the-field_tsvector' already exists.

Running django-tsvector-field 0.9.3, django 1.11, and PostgreSQL 9.5.6

**Comment by willemarcel** [comment]
@cjmochrie I had this problem and solved following the 2nd installation method cited on https://github.com/damoti/django-tsvector-field#installation

**Comment by eukreign** [comment]
@cjmochrie sorry, I didn't see this issue until now. are you still having problems? did you resolve your issue? If you have suggestions on how the documentation can be improved, please let me know.

**Comment by cjmochrie** [comment]
@eukreign Sorry, I will close the issue as I'm not able to contribute right now.

**Comment by vpoulailleau** [comment]
I also used the 2nd installation to finally make it work. Maybe you can consider adding this to the README? By the way, thanks for this project.

**Comment by imbolc** [comment]
The same here
